[project]
name = "infos-n-tasks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "agno>=1.7.9",
    "google-genai>=1.29.0",
    "packaging>=25.0",
    "sqlalchemy>=2.0.42",
]
